spring.application.name=riubackend

# Virtual threads
spring.threads.virtual.enabled=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/riubackend
spring.datasource.username=riuuser
spring.datasource.password=riupassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=kafka:9092

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
