package com.emmanueljeanpierreauguste.riubackend.infrastructure.adapter.in.rest.mapper;

import com.emmanueljeanpierreauguste.riubackend.domain.model.HotelSearch;
import com.emmanueljeanpierreauguste.riubackend.domain.model.SearchCount;
import com.emmanueljeanpierreauguste.riubackend.infrastructure.adapter.in.rest.dto.CountResponse;
import com.emmanueljeanpierreauguste.riubackend.infrastructure.adapter.in.rest.dto.SearchRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for converting between REST DTOs and domain models.
 */
@Mapper(componentModel = "spring")
public interface SearchRestMapper {

    /**
     * Converts a SearchRequest DTO to a HotelSearch domain model.
     * searchId is ignored as it will be generated by the application layer.
     */
    @Mapping(target = "searchId", ignore = true)
    HotelSearch toDomain(SearchRequest request);

    /**
     * Converts a SearchCount domain model to a CountResponse DTO.
     */
    default CountResponse toCountResponse(SearchCount searchCount) {
        return new CountResponse(
                searchCount.searchId(),
                new CountResponse.SearchDetail(
                        searchCount.hotelId(),
                        searchCount.checkIn(),
                        searchCount.checkOut(),
                        searchCount.ages()
                ),
                searchCount.count()
        );
    }
}

